name: Apache-PHP Server
version: "1.0.0"
slug: apache-php-server
description: "Jednoduchý Apache + PHP server pre Home Assistant OS"
startup: services
boot: auto
init: false
hassio_api: false
hassio_role: default
arch:
  - aarch64
  - armv7
  - amd64
url: ""
options: {}
schema: {}
image: ""
